---

name: ZoneService

---

find:
  type: Zone
  args:
    id: integer!

findMany:
  type: [ Zone ]
  args:
    ids: [ integer ]

all:
  type: [ Zone ]
  args:
    index: string
    offset: integer
    limit: integer

---

create:
  type: Zone
  args:
    foo: [ integer ]
    bar: string
    baz: string

update:
  type: Zone
  args:
    id: integer!
    foo: [ integer ]
    bar: string
    baz: string

destroy:
  type: string
  args:
    id: integer!
